### ISSUE TITLE
write an informative readme.md file

### ISSUE THREAD

**Issue by Swanson-Hysell** [Swanson-Hysell-Group/fieldmove-notes-merger#1]
The readme file needs to be edited so that it describes what the code does and how to use it.

**Comment by yuempark** [comment]
sorry - i will edit that soon. i haven't completely finished going through
the code yet.

On Mon, Aug 24, 2015 at 4:14 PM, Nick Swanson-Hysell <
notifications@github.com> wrote:

> The readme file needs to be edited so that it describes what the code does
> and how to use it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Swanson-Hysell-Group/fieldmove-notes-merger/issues/1.

## 

_Yuem Park_
  yuempark@berkeley.edu
  Department of Earth & Planetary Science
  University of California, Berkeley

**Comment by Swanson-Hysell** [comment]
Sounds good. It will be a good chance to get some experience with **Markdown** syntax.

**Comment by Swanson-Hysell** [comment]
Looks good. We can keep adding more details moving forward.
